### ISSUE TITLE
The avatar image should be as per the image size or else they are moving out of the image div

### ISSUE THREAD

**Issue by Sahilll15** [BeforeIDieCode/BeforeIDieAchievements#10]
![Screenshot 2023-08-20 at 1 44 22 PM](https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/109215419/8afb8cfa-9d09-43e9-905c-dee5ae9c8171)

The avatar does not match the image appropriately.

**Comment by XanderRubio** [comment]
Got it, Sahill! I'm currently looking into it. 👍🏻

**Comment by XanderRubio** [comment]
Thanks, Sahil for their issue, and it has been resolved🙏🏻

<img width="1433" alt="Screenshot 2023-08-21 at 16 55 58" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/ac9f4197-2380-4e2f-80ea-5505b43ac279">

**Comment by Sahilll15** [comment]
cool!!! maybe you can assign us such issues

**Comment by XanderRubio** [comment]
Agreed! Will be adding issues this week! Thank you, Sahil!
