### ISSUE TITLE
Add Footer NEEDED 🟢

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#13]
Webapplications is currently missing a footer. For the time being, this project is a single-page application. Degian and integrate a footer with the following message: **Made with 💙 by the Before I Die Community** and from here create a link that links back to this project repository for now. 

<img width="1435" alt="Screenshot 2023-08-22 at 21 02 34" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/6848208f-f34d-4673-8ed4-efee55d9d81c">

### Add animation to the heart by using font awesome open source-free icons. [Font awesome](https://fontawesome.com/search?q=heart&o=r&m=free). 
<img width="1429" alt="Screenshot 2023-08-22 at 21 06 51" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/14060027-a987-4f72-96c7-9697f1bd18ab">

<img width="1429" alt="Screenshot 2023-08-22 at 21 07 01" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/8f034355-07eb-44e6-bdbe-3e44804566ce">

### An example of what one could do for the heart animation from the font-awesome website ⬇️

https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/3f1e2eb8-de28-47b3-bfec-61c0c7742550

**Comment by ghost** [comment]
I would like to work on this issue

**Comment by XanderRubio** [comment]
Hi Girish! Thank you for your enthusiasm and offer to work on this issue. The contributor @lefty93 happened to just send a pull request and I have merged it into the main branch. Please see #19 for further details of the footer being added. 

The current footer at the moment that has been added. ⬇️

<img width="382" alt="Screenshot 2023-08-23 at 17 39 41" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/bbaafec3-ce24-48f7-98a8-854b8176cba2">

That being said, please feel free to contribute your text and info to "What you want to do before you Die?' and/or contribute to the other open issues (I will be adding more every day), please feel free to add more open issues with your own ideas and also I have created a [Roadmap](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/ROADMAP.md) with ideas to add to the project that are both short term and long term focused on building upon this project to get ideas from for creating open issues. Thanks for your enthusiasm, and have a great day and looking forward to seeing your contributions! 😇

**Comment by XanderRubio** [comment]
@lefty93 has successfully resolved this issue from #19 merge. Great work with the heart animation!


<img width="1255" alt="Screenshot 2023-08-23 at 17 51 33" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/3aad34a4-b473-4150-995f-86db2248c764">
