### ISSUE TITLE
[Feature Request] Add a clickable contribution page that displays all members who have contributed to the project.

### ISSUE THREAD

**Issue by MarcianoN** [BeforeIDieCode/BeforeIDieAchievements#135]
### Description

Hello @XanderRubio , i've read the roadmap and i saw this feature idea. I would like to try and make this if possible.
I was wondering if i have the same idea of how to implement this as you.
Adding a button next to the current GitHub button on the homepage. 
After clicking the button you will go to a new page where you see all the contributors. 
Like the screenshot in a grid but ofcourse with the names of the contributor under it and maybe a link to their github page?

-Marciano

### Screenshots

![exampleContributorsGrid](https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/58508529/0b1fd7fa-35f7-4407-9bc2-d58693ed285b)

### Checklist

- [X] I have checked for duplicate [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)
- [X] I have read the [Contribution Guidelines]((https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md))
- [X] I am willing to work on this issue (optional)

**Comment by XanderRubio** [comment]
Hi @MarcianoN,
Thank you for your eagerness to review the ROADMAP and choose a feature to include. You're absolutely correct in suggesting a grid layout and switching your screenshot images to those of contributors, accompanied by a link to their GitHub profile - for now. In the future, we can make this feature more dynamic, allowing contributors to customize the links they display. This would be similar to the layout of CONTRIBUTOR.md. 

Furthermore, another contributor will be adding a new header to the main branch of the homepage later today, which will change the arrangement of the GitHub button on the homepage. Before you begin, I recommend fetching the most recent version of the main branch. Additionally, we can create a feature branch for your issue, which will assist us in reviewing and merging to avoid major merge conflicts. Thanks Marciano!

**Comment by MarcianoN** [comment]
Okay ! 
So if i understood correctly,
for now i'll wait for the header to be made today. Then i can fetch the most recent version of the main branch and start coding?   Also you creating the feature branch for this issue sounds good! 
-Marciano

**Comment by XanderRubio** [comment]
> Okay ! So if i understood correctly, for now i'll wait for the header to be made today. Then i can fetch the most recent version of the main branch and start coding? Also you creating the feature branch for this issue sounds good! -Marciano

Excellent, you are correct in your understanding, and thank you for double-checking, as I could have explained more clearly. Thanks for understanding, and I will message you again in this issue when it is ready to go, and you can begin developing the new feature😇

**Comment by MarcianoN** [comment]
Alright, that sounds good!

**Comment by XanderRubio** [comment]
> Alright, that sounds good!

Hi @MarcianoN, I've gone ahead and added the new header that we have. You can view on the [live link](https://before-i-die-achievements.vercel.app/). You can go ahead and work with this version and additionally create a new feature branch called `feature-contributor-page.` For now, you can first create the layout of your contributors page, and then afterward, we will figure out the button we will have on the main page. Feel free to let me know if I can help with anything, and happy developing!

**Comment by MarcianoN** [comment]
The header looks great!
I'll start working on the page today.

**Comment by XanderRubio** [comment]
Great and have a nice day!

**Comment by MarcianoN** [comment]
Hello, @XanderRubio 
I think i've finished the contributors page,
I will make a pullrequest for it now.
Like you mentioned before, I did not make a button in the homepage so the way to see the page is by typing /Contributors in the URL. 
Please let me know if i did something wrong so i can change it !
Also i was not sure if i did the routing correctly since it was my first time making routes in react.
I had fun making the page!

**Comment by XanderRubio** [comment]
> Hello, @XanderRubio I think i've finished the contributors page, I will make a pullrequest for it now. Like you mentioned before, I did not make a button in the homepage so the way to see the page is by typing /Contributors in the URL. Please let me know if i did something wrong so i can change it ! Also i was not sure if i did the routing correctly since it was my first time making routes in react. I had fun making the page!

Great job, @MarcianoN! It's wonderful to hear that you had a good time and gained practical skills while learning. I'll review everything now and get back to you. I appreciate your enthusiasm and contribution to the project as this is the purpose of the project to assist new developers with continually building on skills!

**Comment by XanderRubio** [comment]
This issue is now closed from pull request #139 and the feature has been merged into the main branch and we will need to create the ability for users to click and find this new `Contributor` page . Great work @MarcianoN and have a look how it looks on the [live link](https://before-i-die-achievements.vercel.app/Contributors). Congratulations on your feature being merged <img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Food/Bottle%20with%20Popping%20Cork.png" alt="Bottle with Popping Cork" width="25" height="25" /><img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Food/Bottle%20with%20Popping%20Cork.png" alt="Bottle with Popping Cork" width="25" height="25" />!!!
