### ISSUE TITLE
[Feature Request] Add a randomization feature to the Contributor Page

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#161]
### Description

Description: When viewing the [Contributor page](https://before-i-die-achievements.vercel.app/Contributors) that utilizes the [Contributors Grid](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/src/Components/ContributorsGrid) component, the contributors' cards should be displayed in a random order every time the page is visited or refreshed. This feature should be similar to the implementation in the [MasonryLayout.jsx](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/Components/MasonryLayout/MasonryLayout.jsx) file on line 23, where the user array is shuffled using the following code snippet:
```
const shuffledUsers = users.sort(() => Math.random() - 0.5);
```

The goal is to apply a similar approach to randomize the order of the contributors' cards on the Contributor page.

### Screenshots

<img width="1160" alt="Screenshot 2023-10-03 at 00 21 16" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/5728533f-c37b-4bea-8737-6317fd3c4172">

### Checklist

- [X] I have checked for duplicate [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)
- [X] I have read the [Contribution Guidelines]((https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md))
- [ ] I am willing to work on this issue (optional)

**Comment by Lozlink** [comment]
Hey, can you please assign this to me. It's already completed and I can create a pull request shortly.
