### ISSUE TITLE
[Feature Request] Make The Scroll to top button a little smaller and transparent.

### ISSUE THREAD

**Issue by MeetThakur** [BeforeIDieCode/BeforeIDieAchievements#164]
### Description

Currently, the 'scroll to top' button occupies a considerable amount of space and overlaps BID images, especially on mobile devices it looks a bit off. Reducing its size and making it more transparent would give it a sleeker appearance and improve the user interface.

### Screenshots

Now
![image](https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/99238677/9c7b3e1b-d0ce-434b-a587-6108c7ecda8f)

After some small changes
![image](https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/99238677/ef3997c3-126d-45e0-9cb5-0bec7a0494ec)

### Checklist

- [X] I have checked for duplicate [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)
- [X] I have read the [Contribution Guidelines]((https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md))
- [X] I am willing to work on this issue (optional)

**Comment by XanderRubio** [comment]
This makes sense as a valuable addition @MeetThakur and this issue is all yours to develop and create a pull request!
