### ISSUE TITLE
[BUG] Can't tap on show random contributor button on small screens 

### ISSUE THREAD

**Issue by MeetThakur** [BeforeIDieCode/BeforeIDieAchievements#175]
### Description

When viewing website on mobile devices the show random contributor button is inaccessible as the text "an open source project" is overlapping it giving a little padding to the text will resolve the issue.

### Screenshots

![image](https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/99238677/64540cb7-e21d-49a3-8d81-f70ebba3d899)

### Checklist

- [X] I have checked for duplicate [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)
- [X] I have read the [Contribution Guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md)
- [X] I am willing to work on this issue (optional)

**Comment by Jothishwar** [comment]
Hi @MeetThakur , I'm willing to work on this issue. Could you assign it to me?

**Comment by MeetThakur** [comment]
@Jothishwar sorry, but I am I already working on it.

**Comment by MeetThakur** [comment]
Sorry, but I am I already working on it.

**Comment by Jothishwar** [comment]
ok cool.

**Comment by XanderRubio** [comment]
Hi @MeetThakur! Excellent find, and absolutely makes sense to improve this. I would also encourage you if ou would like to place the show button with an enhanced UI appearance additionally since, at the moment, it doesn't go well with the site. Thank you for adding this as an open issue, and your good to go ahead with working on this issue and enhancing on the mobile version. Have a great day!

**Comment by XanderRubio** [comment]
> Hi @MeetThakur , I'm willing to work on this issue. Could you assign it to me?

Hi @Jothishwar! Thank you for your enthusiasm to assist and contribute right away to the project. I encourage you to get involved with the project by adding your text and image for what you want to do before you die. You can find this in issue #5 and going through the [CONTRIBUTION-GUIDELINES](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md). Let me know if you have any questions and have a nice day!

Xander

**Comment by MeetThakur** [comment]
@XanderRubio sorry for the delay I am starting my freshman year in college next week I am kinda busy for preparation but I'll fix it within 3-4 days.

**Comment by XanderRubio** [comment]
> @XanderRubio sorry for the delay I am starting my freshman year in college next week I am kinda busy for preparation but I'll fix it within 3-4 days.

Hi @MeetThakur, no worries, and I appreciate your update. Thank you and I wish you a smooth start to your freshman year in college! And when you get around to it over the next 4 days that is great.

**Comment by XanderRubio** [comment]
My apologies, @MeetThakur. I just realized that issue #191 has been created to address the placement of the 'show' button and the appearance of the 'RandomContributor' component. The goal is either to remove the 'show' button to a more favorable position or to replace it with a slide show presentation of contributors on a card display. If you haven't started working on this yet, we can put a pause to it and close this issue. 

Additionally, we may not need to address this issue if we decide to get rid of the 'show' button altogether, as it doesn't fit well with the UI of the website. I apologize for any confusion, and please let me know your thoughts on this matter.

Xander

**Comment by MeetThakur** [comment]
@XanderRubio I haven't Started working on it yet ,I agree on the part that this doesn't go well be the UI so closing this issue will be a good idea.

**Comment by XanderRubio** [comment]
Great, @MeetThakur! Please be on the lookout for more UI issues, and feel free to contribute when you have time. Best of luck with your upcoming studies! I will go ahead and close this issue.

**Comment by XanderRubio** [comment]
Closing issue because issue #191 is enhancing the UI of the `show` button.
