### ISSUE TITLE
[BUG] Solving dependency errors to be able to run code 

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#180]
### Description

This is an issue with the packackages.json, and we would love to have assistance on how to navigate and fix this error so that when cloning this repo for the first time and running `npm i`, the following screenshot doesn't show these errors, and additionally this issue is affecting the preview deployment from being built. 

### Screenshots

<img width="900" alt="Screenshot 2023-10-11 at 16 42 40" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/81962cbc-a587-4069-80e5-6e7e9041061c">

### Checklist

- [X] I have checked for duplicate [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)
- [X] I have read the [Contribution Guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md)
- [ ] I am willing to work on this issue (optional)

**Comment by koleajeolayinka** [comment]
I've looked into the problem with the packages.json file, and I want to help fix it. I understand how crucial it is to have a smooth experience when they clone the repository and deploy the preview.

I'm ready to dig into the issue and find a solution. If you have more details or information that could help, please share. I'll keep you posted on what I find, and once it's sorted, I'll submit a pull request.

Could you please assign this issue to me? I'm eager to contribute to the project. Thanks!

**Comment by XanderRubio** [comment]
> I've looked into the problem with the packages.json file, and I want to help fix it. I understand how crucial it is to have a smooth experience when they clone the repository and deploy the preview.
> 
> I'm ready to dig into the issue and find a solution. If you have more details or information that could help, please share. I'll keep you posted on what I find, and once it's sorted, I'll submit a pull request.
> 
> Could you please assign this issue to me? I'm eager to contribute to the project. Thanks!

Hey @koleajeolayinka! Thank you for your interest in assisting with this issue. I have noticed that another contributor has linked a pull request to this issue. Although it is best practice to wait until the issue is assigned, I will review the pull request to see if it can help solve the problem. Regardless, I plan on creating a few new issues and can tag you ahead of time for the first claim if you would like. I will get back to you soon concerning this issue. I appreciate your time and effort in commenting and asking to be assigned.

**Comment by koleajeolayinka** [comment]
Thank you so much for the update! I really appreciate your guidance. I'm open to being tagged for the first claim on the new issues you plan to create. 💜

**Comment by XanderRubio** [comment]
> Thank you so much for the update! I really appreciate your guidance. I'm open to being tagged for the first claim on the new issues you plan to create. 💜

Excellent! How would you like to assist with adding a button for directing users on the [main page](https://before-i-die-achievements.vercel.app/) to the [Contributors Map](https://before-i-die-achievements.vercel.app/contributors-map) page? 
I have assigned you to issue #182

**Comment by XanderRubio** [comment]
This issue has been successfully closed by contributor @ben-dh3 from pull request #181
