### ISSUE TITLE
[Feature Request] Create button to direct to Contributor Page 

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#182]
### Description

Please create a button on the website's [main page](https://before-i-die-achievements.vercel.app/) to direct users to the [Contributor Page](https://before-i-die-achievements.vercel.app/contributors-map).

Ideally, place the Contributors Button Below the Contributors button and title it `CONTRIBUTORS MAP` and also rename the `CONTRIBUTORS` button to `CONTRIBUTORS LIST.` For now, please keep it the same style as the other buttons. Thank you!

### Screenshots

Please place the button here:
<img width="1261" alt="Screenshot 2023-10-12 at 00 25 46" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/8c6beca0-34db-4b6d-8b4d-f0f3f2a2f229">

It will direct you to this page:

<img width="1267" alt="Screenshot 2023-10-12 at 00 27 05" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/defcc321-a203-41e7-a1d8-5e13aa89a900">

### Checklist

- [X] I have checked for duplicate [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)
- [X] I have read the [Contribution Guidelines]((https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md))
- [ ] I am willing to work on this issue (optional)

**Comment by XanderRubio** [comment]
@koleajeolayinka, please confirm you can work on this issue please! 😇

**Comment by 1devmaaz** [comment]
Can I get assigned, mate?

**Comment by koleajeolayinka** [comment]
Hi @XanderRubio ,

Thank you for bringing this to my attention. I confirm my commitment to work on the requested feature. I will keep you updated on the progress
Sorry for getting back to you late. Thanks for your understanding. 💜

**Comment by XanderRubio** [comment]
> Hi @XanderRubio ,
> 
> Thank you for bringing this to my attention. I confirm my commitment to work on the requested feature. I will keep you updated on the progress Sorry for getting back to you late. Thanks for your understanding. 💜

Excellent @koleajeolayinka! Much appreciated and no worries!

**Comment by XanderRubio** [comment]
> Can I get assigned, mate?

Hi, @maazshakeel again! You are very enthusiastic to contribute. This is great! Tackle issue #5 first and then we can also think of a feature you can add that your interested since your learning on AI to the Before I Die code.
