### ISSUE TITLE
[Feature Request] Add footer to other two pages 

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#183]
### Description

Please add the footer from the main to be displayed on the [Contributor Map](https://before-i-die-achievements.vercel.app/contributors-map) page and, additionally, the [Contributors list](https://before-i-die-achievements.vercel.app/contributors) page. 

The footer component can be found here. 

Please let me know if you have any questions, and please wait to ask to be assigned, then be assigednd then work on the addition and submit your pull request. Thank you! 

### Screenshots

Footer from main:
<img width="1243" alt="Screenshot 2023-10-12 at 00 32 18" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/4bdb5a04-dc43-4c6a-afca-c434fc5d4bea">

Place this footer on these two pages additionally:
<img width="1266" alt="Screenshot 2023-10-12 at 00 33 01" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/75e39464-398e-42b9-9fac-3ef25133b2d9">
<img width="1269" alt="Screenshot 2023-10-12 at 00 33 35" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/f674a757-2d9e-4ab1-9941-0a5d770b67e9">

### Checklist

- [X] I have checked for duplicate [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)
- [X] I have read the [Contribution Guidelines]((https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md))
- [ ] I am willing to work on this issue (optional)

**Comment by LynxSumit** [comment]
Need a design pattern tu make footer !

**Comment by sumit-022** [comment]
I want to contribute to this, Please assign me the task

**Comment by shreyanshig** [comment]
Hi @XanderRubio, Could you please assign this task to me?

**Comment by XanderRubio** [comment]
> Need a design pattern tu make footer !

Hi @LynxSumit! The issue has been assigned since you were the first to respond. Can you do this? For now, you just need to add the current footer to the pages in [Contributors.jsx](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/pages/Contributors.jsx) and [LocationContributorsMap.jsx](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/pages/LocationContributorsMap.jsx). We will, later on, build out the design of the Footer more later on and this issue is for placing the footer to show up on other pages that currently exist. Let me know soon if you can do this issue. Thank you!

**Comment by XanderRubio** [comment]
> I want to contribute to this, Please assign me the task

HI @sumit-022! Thank you for your enthusiasm and for now the issue has been assigned to @LynxSumit and you will be next in line for this issue if no confirmation is given from him that he will be working on it. I would recommend working on issue #5 to contribute right away to the project and also learn more in the process. Have a great day!

**Comment by LynxSumit** [comment]
> > Need a design pattern tu make footer !
> 
> Hi @LynxSumit! The issue has been assigned since you were the first to respond. Can you do this? For now, you just need to add the current footer to the pages in [Contributors.jsx](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/pages/Contributors.jsx) and [LocationContributorsMap.jsx](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/pages/LocationContributorsMap.jsx). We will, later on, build out the design of the Footer more later on and this issue is for placing the footer to show up on other pages that currently exist. Let me know soon if you can do this issue. Thank you!

Hello, @XanderRubio , yeah sure picking this up, just the only question i have is what the structure of footer will look like?

**Comment by XanderRubio** [comment]
> Hi @XanderRubio, Could you please assign this task to me?

Hi @shreyanshig! Thank you for your enthusiasm in wanting to tackle this issue. You are currently number three in line if the other two contributors ahead of you don't work on it. I would recommend working on issue #5 to contribute right away to the project and learn more about the Before I Die code in the process. Let me know if you have any questions and have a nice day!

**Comment by XanderRubio** [comment]
> > > Need a design pattern tu make footer !
> > 
> > 
> > Hi @LynxSumit! The issue has been assigned since you were the first to respond. Can you do this? For now, you just need to add the current footer to the pages in [Contributors.jsx](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/pages/Contributors.jsx) and [LocationContributorsMap.jsx](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/pages/LocationContributorsMap.jsx). We will, later on, build out the design of the Footer more later on and this issue is for placing the footer to show up on other pages that currently exist. Let me know soon if you can do this issue. Thank you!
> 
> Hello, @XanderRubio , yeah sure picking this up, just the only question i have is what the structure of footer will look like?

Great! The structure of the footer can be found in the [Footer component](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/src/Components/Footer).

**Comment by XanderRubio** [comment]
Issue has been successfully merged from contributor @sumit-022 pull request #189
