### ISSUE TITLE
[Feature Request] Randomize the color of text being displayed everytime when visiting 

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#184]
### Description

This is to randomize the text color displayed for the `Location of Contributors` on the [Contributors Map](https://before-i-die-achievements.vercel.app/contributors-map) page. 

For this, you will need to work in the [MapContributors](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/src/Components/MapContributors) component and look at the [ContributorsGrid.jsx](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/Components/ContributorsGrid/ContributorsGrid.jsx) to model for implementing a get different colors function. 

Let me know if you have any questions. 

### Screenshots

Make the `Location of Contributors` change colors every time you refresh and view the page. 
<img width="1259" alt="Screenshot 2023-10-12 at 00 45 38" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/226db9c2-55e1-4ac5-bba4-a553fd449e69">

### Checklist

- [X] I have checked for duplicate [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)
- [X] I have read the [Contribution Guidelines]((https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md))
- [ ] I am willing to work on this issue (optional)

**Comment by DanielZhang111** [comment]
Can i get assigned?

**Comment by XanderRubio** [comment]
Hi @DanielZhang111, Good to go and have at it!

**Comment by DanielZhang111** [comment]
Thanks!

**Comment by DanielZhang111** [comment]
I'm kind of confused on how to do this... Could I get some tips?

Sorry I'm kind of new to programming - just a freshman

**Comment by XanderRubio** [comment]
> I'm kind of confused on how to do this... Could I get some tips?
> 
> 
> 
> Sorry I'm kind of new to programming - just a freshman

Of course, I'm logging off for the night and I will assist tomorrow 👍🏻

**Comment by DanielZhang111** [comment]
Ok thanks :)

**Comment by 1devmaaz** [comment]
Can I work on this issue, Xander?

**Comment by XanderRubio** [comment]
> Can I work on this issue, Xander?

Hi @maazshakeel! Thanks for your enthusiasm! The issue you mentioned has been assigned to @DanielZhang111, who is currently working on it. In the meantime, I recommend contributing to issue #5 to get a better understanding of the project and start contributing. I'll be adding more UI-related issues in the coming days. Also, I noticed that you're interested in learning about AI. This repository is a great place to practice and improve your skills in a collaborative and open environment. Have a great day!

**Comment by 1devmaaz** [comment]
Great, thanks mate! Would love to contribute 🙌

**Comment by XanderRubio** [comment]
> I'm kind of confused on how to do this... Could I get some tips?
> 
> Sorry I'm kind of new to programming - just a freshman

HI @DanielZhang111, so for going about this issue one potenail way would be to do the following:

Recreating the getDifferentColors function from the [ContributorsGrid component file](), you can simply recreate the function in the [MapContributors component file](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/Components/MapContributors/MapContributors.jsx). The getDifferentColors function doesn't rely on any local state or props of the ContributorsGrid component, so it can be defined and used in any component. This isn't the most effienct way to resuse a function in React components but it is an easy option to implement. Let me know if this helps. This is the function you would place in the the [MapContributors component file](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/Components/MapContributors/MapContributors.jsx):
```Javascript
const getDifferentColors = () => {
  const r = Math.floor(Math.random() * 256);
  const g = Math.floor(Math.random() * 256);
  const b = Math.floor(Math.random() * 256);
  return `rgba(${r},${g},${b},0.8)`;
};
```

And then you would need to add it to the p tag:
```Javascript
<p className={styles["contributor-title"]}>Location of Contributors</p>
```

Let me know if you have more questions and you got it, Daniel!

**Comment by XanderRubio** [comment]
> Great, thanks mate! Would love to contribute 🙌

Great open your first pull request for issue #188 and I will review and get it merged right away for you!

**Comment by 1devmaaz** [comment]
Sure. (I'll do it tomorrow gotta get some sleep)

**Comment by XanderRubio** [comment]
> Sure. (I'll do it tomorrow gotta get some sleep)

Yes! Sleep is important😉

**Comment by DanielZhang111** [comment]
Ok I'll try that later :)

**Comment by XanderRubio** [comment]
> Ok I'll try that later :)

Great!

**Comment by 1devmaaz** [comment]
Opened pull request!

Contributed to issue [#196 5](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues/5)

**Comment by XanderRubio** [comment]
> Opened pull request!
> 
> 
> 
> Contributed to issue [#196 5](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues/5)

@maazshakeel Excellent! I will be reviewing shortly!

**Comment by 1devmaaz** [comment]
Looking forward to it!

**Comment by jayprakash25** [comment]
Is this issue resolved? ...else can i start working on this

**Comment by XanderRubio** [comment]
> Is this issue resolved? ...else can i start working on this

Hi @jayprakash25. Confirming this issue is already being worked on by @DanielZhang111. I would recommend to contribute go ahead and work on issue #188 to get involved right away.

**Comment by jayprakash25** [comment]
Sure!!

**Comment by XanderRubio** [comment]
> Sure!!

Excellent!

**Comment by jayprakash25** [comment]
I have done a pr ...kindly check it

**Comment by XanderRubio** [comment]
Hi @jayprakash25 . I'm currently traveling and once settled I will review. Thank you!

**Comment by DanielZhang111** [comment]
I did not finish it sorry. I do not know how to do this :(

**Comment by XanderRubio** [comment]
> I did not finish it sorry. I do not know how to do this :(

All good @DanielZhang111. I recommend help with getting familiar with contributing to open source go ahead with sharing what you want to do before you die by working on issue #188. This will help, and also you can contribute right away by opening a pull request by following along in the [CONTRIBUTION-GUIDELINES.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md). 

No worries; you are always welcome to continue tackling a problem. You got this, and I will reassign this issue to another contributor in the meantime and go ahead with sharing your text and image for what you want to do before you die in the meantime. That way, you can also join the Before I Die organization. Have a nice day!

**Comment by XanderRubio** [comment]
> Is this issue resolved? ...else can i start working on this

Hi, @jayprakash25! Are you still interested in working on this issue?

**Comment by harmit17** [comment]
@XanderRubio I would like to work on this issue. I am new to open-source contributions. I have just registered with Hacktoberfest.

**Comment by XanderRubio** [comment]
Excellent! You got it, @harmit17, and happy developing!

**Comment by harmit17** [comment]
Thank you :)

**Comment by DanielZhang111** [comment]
Thanks for the suggestion @XanderRubio. I will consider it! :)

**Comment by jayprakash25** [comment]
I would like to contribute

**Comment by harmit17** [comment]
Hey, @XanderRubio, I think CSS is overriding whatever changes I make to change the color after the page refreshes. I have also removed the blue color from the module.css file. When I inspect it shows me a blue color in the module.css file. What should I do? Any suggestion or hint? 

<img width="1280" alt="open source" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/46776916/0476af62-44fe-4b6a-b890-abe8ea2b9cac">

I am also getting error for ( fetch(
      `https://api.opencagedata.com/geocode/v1/json?q=${encodeURIComponent(
        location
      )}&key=${apiKey}`). 

<img width="1267" alt="image" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/46776916/f80d1e4d-1cd0-4ae6-85b2-169c1218b3db">

**Comment by XanderRubio** [comment]
> Hey, @XanderRubio, I think CSS is overriding whatever changes I make to change the color after the page refreshes. I have also removed the blue color from the module.css file. When I inspect it shows me a blue color in the module.css file. What should I do? Any suggestion or hint?
> 
> <img alt="open source" width="1280" src="https://user-images.githubusercontent.com/46776916/276305392-0476af62-44fe-4b6a-b890-abe8ea2b9cac.png">
> I am also getting error for ( fetch( `https://api.opencagedata.com/geocode/v1/json?q=${encodeURIComponent( location )}&key=${apiKey}`).
> 
> <img alt="image" width="1267" src="https://user-images.githubusercontent.com/46776916/276342212-f80d1e4d-1cd0-4ae6-85b2-169c1218b3db.png">

Hi, @harmit17, The reason you are getting the fetch error is that you don't have the API keys while working on your local dev server. The API keys have been added to the environmental variables in the project repository for security purposes. However, you don't need to worry about the fetch error for now, since we are only focusing on adding randomization to the text. 

I would suggest you take a look at the code structure that applies the randomization to the [Contributor List here](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/Components/ContributorsGrid/ContributorsGrid.jsx). Specifically, check the function that starts on `line 5`. If you need further assistance, please don't hesitate to let me know.

**Comment by XanderRubio** [comment]
> I would like to contribute

Hello @jayprakash25! I apologize for not passing this issue to you earlier, as I know you had requested it previously. You will be given priority for the next opportunity to contribute if we need to pass on this issue to someone else. Your eagerness to help and assist is much appreciated. Moreover, feel free to add your own open issue to the project. Thank you!

**Comment by harmit17** [comment]
@XanderRubio Thanks for clearing the doubt.  I will try again and let you know. 

I tried it, even if I commented on the blue color in the module.css file. The color stayed the same. I defined the function in the component and added style to the tag.

**Comment by XanderRubio** [comment]
> @XanderRubio Thanks for clearing the doubt. I will try again and let you know.
> 
> I tried it, even if I commented on the blue color in the module.css file. The color stayed the same. I defined the function in the component and added style to the tag.

I would need to look deeper into this; however, my time today and tomorrow needs to be focused on my other work tasks. Would you like me to ask for another contributor to help out? I know @jayprakash25 would like to help you out. You can create a pull request with what you have at this point, and we can have a look at your code that way. Let me know😇

**Comment by harmit17** [comment]
> > @XanderRubio Thanks for clearing the doubt. I will try again and let you know.
> > I tried it, even if I commented on the blue color in the module.css file. The color stayed the same. I defined the function in the component and added style to the tag.
> 
> I would need to look deeper into this; however, my time today and tomorrow needs to be focused on my other work tasks. Would you like me to ask for another contributor to help out? I know @jayprakash25 would like to help you out. You can create a pull request with what you have at this point, and we can have a look at your code that way. Let me know😇

I think I have completed the feature request. It was my mistake in reviewing the code. I kept looking at the hosted page when I ran the code. I am creating a pull request.

**Comment by XanderRubio** [comment]
> > > @XanderRubio Thanks for clearing the doubt. I will try again and let you know.
> > > I tried it, even if I commented on the blue color in the module.css file. The color stayed the same. I defined the function in the component and added style to the tag.
> > 
> > 
> > I would need to look deeper into this; however, my time today and tomorrow needs to be focused on my other work tasks. Would you like me to ask for another contributor to help out? I know @jayprakash25 would like to help you out. You can create a pull request with what you have at this point, and we can have a look at your code that way. Let me know😇
> 
> I think I have completed the feature request. It was my mistake in reviewing the code. I kept looking at the hosted page when I ran the code. I am creating a pull request.

Oh yes, I understand. Sometimes, when I perform code reviews and switch to the Contributors List or Contributors Map page, I forget to make sure I'm viewing it on the preview link and end up on the live site instead. Thanks for letting me know. Once you create the pull request, I'll take a look as soon as possible!

**Comment by harmit17** [comment]
@XanderRubio I have created a pull request. Please look into it whenever you get time. Thank you.

**Comment by XanderRubio** [comment]
> @XanderRubio I have created a pull request. Please look into it whenever you get time. Thank you.

Great! Looking now!
