### ISSUE TITLE
[Feature Request] Change text font to be Chalk-3

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#185]
### Description

Please change the font of `Before I Die...` found in the [MasonryBox](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/Components/MasonryLayout/MasonryBox/MasonryBox.jsx) component and use the Chalk-3 font. 

Let me know if you have any questions!

### Screenshots

<img width="1255" alt="Screenshot 2023-10-12 at 00 56 13" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/a80f9df7-e2d9-43fa-b8c3-6fabae27cfde">

### Checklist

- [X] I have checked for duplicate [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)
- [X] I have read the [Contribution Guidelines]((https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md))
- [ ] I am willing to work on this issue (optional)

**Comment by DiguyaDeveloper** [comment]
The need is to change the font of the title Before i die, correct?
Could you sign this issue for me, please?

**Comment by XanderRubio** [comment]
> The need is to change the font of the title Before i die, correct? Could you sign this issue for me, please?

That is correct nice and easy!

**Comment by XanderRubio** [comment]
You're good to go and do what you need to do👍🏻

**Comment by DanielZhang111** [comment]
Is there anything else I can do for this for it to count as a pull/merge req?

**Comment by DiguyaDeveloper** [comment]
I don't think so, can you please review?

**Comment by XanderRubio** [comment]
> Is there anything else I can do for this for it to count as a pull/merge req?

HI, @DanielZhang111 contributor @DiguyaDeveloper has completed and closed this issue from pull request #186. Thank you for your enthusiasm!
