### ISSUE TITLE
[Feature Request] Move a section of the header to improve UI 

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#190]
### Description

Please level out the below section so that the `Contributors Map` at the bottom of the button lines up with the bottom of the [dummy_image](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/public/img/dummy_image) box. Please see the below image. 

### Screenshots

<img width="1440" alt="Screenshot 2023-10-12 at 16 46 01" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/92abd09a-2088-4ae9-96cc-2316051107cf">

### Checklist

- [X] I have checked for duplicate [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)
- [X] I have read the [Contribution Guidelines]((https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md))
- [ ] I am willing to work on this issue (optional)

**Comment by yashj09** [comment]
can you assign me this issue

**Comment by XanderRubio** [comment]
Good to go @yashj09, and thank you for your enthusiasm!

**Comment by yashj09** [comment]
hi i have made the change you asked for , how it is looking , and should i raise PR. @XanderRubio 
![image](https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/118172073/05b4fbd6-2481-4e0c-a0d8-a19d3cb22b2d)

**Comment by XanderRubio** [comment]
Much better, and go ahead with creating a PR! Thank you kindly @yashj09!
