### ISSUE TITLE
[BUG] heartBeat and typing sound effects does not work correctly 

### ISSUE THREAD

**Issue by negar-75** [BeforeIDieCode/BeforeIDieAchievements#207]
### Description

in the footer component, the heartBeat and  typing sound effects should work properly onMouseEnter and onMouseLeave but they don't.

### Checklist

- [X] I have checked for duplicate [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)
- [X] I have read the [Contribution Guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md)
- [X] I am willing to work on this issue (optional)

**Comment by XanderRubio** [comment]
Exellent @negar-75! Reviewing your PR now!

**Comment by XanderRubio** [comment]
@negar-75 are you interested in working on another UI issue for the site?

I want to improve the UI for this section, which is the [RandomContributor](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/src/Components/randomcontributor) component. 
<img width="1440" alt="Screenshot 2023-10-16 at 21 11 36" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/b9e3970b-01d4-4233-9de5-f1fdb3bfa10c">

**Comment by negar-75** [comment]
I will go for it but before it I want to implement lazy loading for component for aiming better performance and reduce the rendering time !
what do you think about it?

**Comment by XanderRubio** [comment]
> I will go for it but before it I want to implement lazy loading for component for aiming better performance and reduce the rendering time ! what do you think about it?

Yes and even better! Am I correct in remembering that you wrote about this several days ago on an issue you brought up before? Regardless it is a great idea to speed up the loading time, and this would be a massive enhancement on the UX. Great idea! Once you create the issue I will go ahead with assigning the issue to you👍🏻
