### ISSUE TITLE
🟢 Update the Contribution Guidelines to reflect the new CONTRIBUTORS.md 

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#25]
Need to add a to the [CONTRIBUTION-GUIDELINES](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md) to mention that the [CONTRIBUTORS.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTORS.md) needs to explain how there is only to be a maximum of seven contributors per each column and that when a contributors is contributing and sees already column displayed above that they need to then close the </td> and create a new <td> tag. Give an example of this with a code block. 

🚨This explanation needs to be added to [Step 8 of the CONTRIBUTION-GUIDELINES](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md#step-8-add-to-the-contributorsmd-file)🚨

### Consider adding this text:

**To add a new row to the table in the given markdown file, follow these steps:**

1. Copy the last row of the table, including the <tr> and </tr> tags.
2. Paste the copied row below the last row of the table.
3. Replace the content of the cells in the new row with the information of the new contributor.
4. Make sure to update the column number in the <td> tags to match the number of columns in the table.

For example, if the last contributor was in column 7 and you want to add a new row with a new contributor, you would copy the last row of the table, paste it below the last row, and update the content of the cells with the information of the new contributor. You would also need to update the column number in the <td> tags to 8, since you are adding a new column.

- [ ] take away the alt text from the code in CONTRIBUTORS.md
- [ ] add to the CONTRIBUTION-GUIDELINES

**Comment by Nawarajkarki** [comment]
I noticed that we're currently using `##` for the "Step's" heading. To improve the document structure and readability, I suggest we change this to an `#` heading. This would make it stand out more as a major step in the process. Here's the difference.


## Step 8. ADD to the CONTRIBUTORS.md file
# Step 8. ADD to the CONTRIBUTORS.md file

**Comment by XanderRubio** [comment]
> I noticed that we're currently using `##` for the "Step's" heading. To improve the document structure and readability, I suggest we change this to an `#` heading. This would make it stand out more as a major step in the process. Here's the difference.
> 
> ## Step 8. ADD to the CONTRIBUTORS.md file
> # Step 8. ADD to the CONTRIBUTORS.md file

Hi @Nawarajkarki

Thank you for showing interest in helping with the Before I Die Code project. Can you please provide more information as I am not entirely sure how your suggestion would improve the documentation, as the steps are already marked with `##` in the markdown file and are quite prominent. If you are suggesting that we mark each step with `#` for increased size, that is a possibility. However, before addressing this issue, I would recommend reading the [README](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/README.md) and going through the [CONTRIBUTION-GUIDELINES.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md). Once you have done that, please feel free to open your first pull request and share your goals for the project. Looking forward to your contribution and have a nice day!

Xander
