### ISSUE TITLE
🟢 Arabic Translation NEEDED for Documentation

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#29]
Arabic translation is needed for the following files: 

- [x] [README](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/README.md)
- [x]  [CODE_OF_CONDUCT](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CODE_OF_CONDUCT.md) 
- [x]  [CONTRIBUTION-GUIDELINES.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md)
- [x]  [LICENSE](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/LICENSE)
- [x] [about.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/about.md)

Please add these files in the empty [Arabic section](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/translations/Arabic).

And please work off the branch [arabic-translation](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/arabic-translation) for organization purposes.

Modeling after the [GitHub Repository first-contributors](https://github.com/firstcontributions/first-contributions)
<img width="1057" alt="Screenshot 2023-08-24 at 02 26 10" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/40a7d3f7-7bcc-4173-8ff3-0173f858fa05">

**Comment by Yor-dan** [comment]
Hi, can I help with this?

**Comment by XanderRubio** [comment]
> Hi, can I help with this?

Hi @Yor-dan

Thank you for your enthusiasm in wanting to tackle this issue of the formatting of documents. Yes, this would help us get closer to translating the docs to all top six languages from our [Milestones](https://github.com/BeforeIDieCode/BeforeIDieAchievements/milestones). I have gone ahead and assigned you to this issue.
