### ISSUE TITLE
🟢 French Translation NEEDED for Documentation

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#31]
French translation is needed for the following files: 

- [x] [README](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/README.md)
- [x]  [CODE_OF_CONDUCT](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CODE_OF_CONDUCT.md) 
- [x]  [CONTRIBUTION-GUIDELINES.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md)
- [x]  [LICENSE](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/LICENSE)
- [x] [about.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/about.md)

Please add these files in the empty [French section](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/translations/French).

And please work off the branch [french-translation](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/french-translation) for organization purposes.

Modeling after the [GitHub Repository first-contributors](https://github.com/firstcontributions/first-contributions)
<img width="1057" alt="Screenshot 2023-08-24 at 02 26 10" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/40a7d3f7-7bcc-4173-8ff3-0173f858fa05">

**Comment by lucasfirmo62** [comment]
Hello @XanderRubio , I really liked this issue, I would like to contribute! Can you make me Assignees?

**Comment by XanderRubio** [comment]
Hi @lucasfirmo62!

Of course! Thank you for reaching out, and I will go ahead and assign this issue to you! Have a great day!

- Xander

**Comment by lucasfirmo62** [comment]
Hi @XanderRubio, everything is done, I'm waiting for you to allow the commit on the branch!

**Comment by XanderRubio** [comment]
Hi @lucasfirmo62, great for you to add your contribution. You will need to open a pull request from the branch you were working on, and then we can review your work and add it to the main branch. Following the [CONTRIBUTION-GUIDELINES.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md) will walk you through how to make a pull request after adding what you want to do before you die text and also image. After committing to your forked version, you can open a pull request from your forked repo of Before I Die Code. See the image below. Please let me know if I can help further😇 Have a great day! 

<img width="1260" alt="Screenshot 2023-09-06 at 14 19 59" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/7f43a075-3bad-444a-88a1-37dd0f710495">

<img width="1440" alt="Screenshot 2023-09-06 at 14 20 15" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/8107acf5-9d3c-48ca-89c7-2da8569b3bbf">
