### ISSUE TITLE
🟢 Mandarin Chinese Translation NEEDED for Documentation

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#32]
Mandarin_Chinese translation is needed for the following files: 

- [x] [README](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/README.md)
- [x]  [CODE_OF_CONDUCT](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CODE_OF_CONDUCT.md) 
- [x]  [CONTRIBUTION-GUIDELINES.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md)
- [x]  [LICENSE](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/LICENSE)
- [x] [about.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/about.md)

Please add these files in the empty [Mandarin_Chinese section](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/translations/Mandarin_Chinese).

And please work off the branch [mandarin-chinese-translation](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/mandarin-chinese-translation) for organization purposes.

Modeling after the [GitHub Repository first-contributors](https://github.com/firstcontributions/first-contributions)
<img width="1057" alt="Screenshot 2023-08-24 at 02 26 10" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/40a7d3f7-7bcc-4173-8ff3-0173f858fa05">

**Comment by EniacTNB** [comment]
Greate for New Coder！
@EniacTNB  will solove it @XanderRubio 
PR is expected to be submitted within one week.

**Comment by XanderRubio** [comment]
Hello @EniacTNB! Thank you for showing enthusiasm and interest in issue #32. I have assigned this issue to you. Please feel free to share any new ideas to improve the Before I Die Code. Additionally, make sure to check out the [README](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/README.md) to better understand the project and complete issue #5 first in order to contribute your image and answer about what you want to do before you die. Have a wonderful day! 

Best regards, 
Xander

**Comment by XanderRubio** [comment]
Pull request #70 has successfully closed this issue from contributor @EniacTNB
