### ISSUE TITLE
🔴 Note add a docker file 

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#46]
As a reminder, think of adding a YAML file for containerization with Docker.

**Comment by SimardeepSingh-zsh** [comment]
Hey Xander, 

I would be glad to help in this issue. Please assign this to me. 

Regards,
Simardeep Singh

**Comment by XanderRubio** [comment]
HI @SimardeepSingh-zsh 

I hope you are doing well. Regarding this issue, I have created a note to add a Dockerfile in the future. Currently, there isn't much to add, but I will assign it to you so you can build out the file and add any necessary information. Thank you for your help, and please let me know if you have any questions. Have a nice day!

Xander

**Comment by SimardeepSingh-zsh** [comment]
docker build -t beforeidieachievements .

**Comment by XanderRubio** [comment]
successfully closed by pull request #137 from contributor @SimardeepSingh-zsh
