### ISSUE TITLE
🟢 Enhance the CONTRIBUTION GUIDELINES documentation for step 5

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#47]
There is a need for clarity in the [contribution guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md) on sharing and writing meaningful text and images to represent contributors. 

This issue is related to feedback from contributor @ccelest1, mentioning that there should be clearer [contribution guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md )about what people should post in terms of what they want to do before they die to ensure the application and project continue developers in the direction of professional and managing in the value it creates for users and developers. 

I think it's recommended to enhance the description of step 5 in the [contribution guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md). Please take a look at the image below to explain. ⬇️ 
<img width="1069" alt="Screenshot 2023-08-30 at 18 42 07" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/2ceafbf8-975b-4777-b3b9-db874a7a0a99">

This issue can draw inspiration for crafting the descriptive text from the following:
1. Reflect on Your Goals and Aspirations:

- Take time to contemplate and identify what you want to accomplish or experience in your lifetime.
- Consider both personal and professional goals, adventures, relationships, and personal growth.
- Reflect on what truly matters to you and what brings meaning and fulfillment to your life.

2. Thoughtful and Meaningful Expression:

- When sharing your goals and aspirations, be thoughtful in your choice of words and images.
- Craft your message in a way that conveys the significance and value of your aspirations.
- Share your motivations, the reasons behind your goals, and how they align with your values.
- Consider using imagery that represents the beauty of life, the diversity of experiences, and the joy of pursuing meaningful goals.

3. Consider the Audience:
Keep in mind that your text and images will be shared publicly, so consider the impact on others.
Be respectful and sensitive to different perspectives and experiences.
Aim to inspire and uplift others with your goals and aspirations, rather than imposing them.
4. Share with Intention:

- Choose the appropriate platforms or channels to share your goals and aspirations.
- Consider sharing with supportive communities, friends, or family who can provide encouragement and support.
- Engage in meaningful conversations and discussions around your shared goals, fostering connections and mutual inspiration.

5. Regularly Review and Update:

- Revisit your goals periodically to ensure they still resonate with you and reflect your evolving aspirations.
- Regularly review your progress and make adjustments as needed.
- Celebrate milestones and share updates with your community, inspiring others through your journey.

Remember, sharing your goals and aspirations is a personal choice. Consider what feels right for you and how you can authentically express your desires while respecting the privacy and feelings of others.

Drawing inspiration from [The Before I Die I Want to Project](https://beforeidieproject.com/about/)

**Comment by CBID2** [comment]
Hey @XanderRubio! 😊 Can I help you with this?

**Comment by XanderRubio** [comment]
HI @CBID2 

Thank you for your enthusiasm and of course! I will go ahead and assign it to you. Please let me know if you have any questions and if will help also if you contribute your before you die text and image by following the [CONTRIBUTION-GUIDELINES.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md) first. To understand the project better. Thank you Christine and have a great day! 

Xander

**Comment by CBID2** [comment]
Hey @XanderRubio! :) I made the PR. It's #91

**Comment by XanderRubio** [comment]
> Hey @XanderRubio! :) I made the PR. It's #91

Excellent @CBID2! I will be reviewing shortly.

**Comment by XanderRubio** [comment]
@CBID2 Great work!
