### ISSUE TITLE
auto translation for "before I die " title based on IP

### ISSUE THREAD

**Issue by negar-75** [BeforeIDieCode/BeforeIDieAchievements#54]

**Comment by XanderRubio** [comment]
Create the ability for the `Before I Die...` text displayed in the `const presetText` variable inside the [MasonryBox.jsx file](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/Components/MasonryLayout/MasonryBox/MasonryBox.jsx) text box to automatically translate to a user/viers IP address. This is being worked on by @negar-75. Thank you and please work on branch [feature-auto-translation-before-i-die](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/feature-auto-translation-before-i-die).
<img width="1224" alt="Screenshot 2023-09-03 at 23 11 59" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/5f281e62-89af-4df7-8046-779fedc732ab">

**Comment by negar-75** [comment]
hey @XanderRubio 
when I wanted to push my commits in" feature-auto-translation-before-i-die "
I was warned by this:
![Screenshot 2023-09-05 105225](https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/113235504/925147cc-cf87-408b-999a-657ec4d96776)

**Comment by XanderRubio** [comment]
@negar-75 Thanks for letting me know. I got this to work for myself after forking the Before I Die repo on my GitHub account and would get the same error. I had to add an SSh key to my GitHub personal account in the settings and this maybe what you need to do even after you have forked the Before I Die Code Repo and then successfully added a test file to a pull request to the Before I Die Code Repo #61 

I was getting the error when attempting to fetch the remote (which is the most updated version of the Before I Die Code repo) ⬇️
` git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.`


Can you run `git fetch upstream` and not get an error in your console?

If you get an error in the console, I can help you add the SSH to your GitHub account😎

**Comment by XanderRubio** [comment]
This is now closed ✅ thanks to @negar-75 from her pull request #67 and was merged into the main branch from commit [a4a46d3](https://github.com/BeforeIDieCode/BeforeIDieAchievements/commit/a4a46d37e6f1dad9a20a9add50284b474cde1e63)
