### ISSUE TITLE
🎨 Automatically Center Contributor's Text in MasonryBox Component

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#77]
**Problem:** 
In the MasonryBox component of our open-source project, we want to ensure that the contributor's text is automatically centered, regardless of whether the text is long or short. Currently, the text is centered nicely for contributors with long text (see examples below), but not for those with short text.
<img width="1322" alt="Screenshot 2023-09-13 at 23 19 51" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/c1ed0cc5-ae6d-4886-8830-7d513f505726">
<img width="1364" alt="Screenshot 2023-09-13 at 23 19 34" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/78c5ca4c-aa74-459e-b7a4-b1f0fb667790">

And here are examples of contributors' text being short, and we want to create code and reform in to enhance and also display text even if it is short, centered automatically in proportion with the masornytext box. 
<img width="1425" alt="Screenshot 2023-09-13 at 23 22 03" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/18706ade-3d48-4eec-8337-c3aaca1f292a">
<img width="1418" alt="Screenshot 2023-09-13 at 23 21 48" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/38931bf4-51b8-47a2-b583-c011f3f89c21">

**Solution**:
PLEASE NOTE THAT THE IMAGES ABOVE WERE IN 100% BROWSER VIEW. PLEASE VIEW IN 100% AND THEN REASSESS WHICH CONTRIBUTORS TEXT NEEDS TO BE CENTERED BECAUSE OF SHORT TEXT
You will need to work inside the [MasonryBox](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/src/Components/MasonryLayout/MasonryBox) folder and enhance the [MasonryBox.jsx](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/Components/MasonryLayout/MasonryBox/MasonryBox.jsx) and [MasonryBox.module.css](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/Components/MasonryLayout/MasonryBox/MasonryBox.module.css)
The solution should involve creating a dynamic style that takes into account the number of characters in the input text. If the text is below a certain length, the style should automatically center the "Before I Die" text and the contributor's text within the MasonryBox component. This revised version provides a clear title for the issue, separates the problem and solution sections, and includes direct links to the example images. It also clarifies the expected outcome and the files that need to be modified.

**Comment by Angeltheesoto** [comment]
Hello, correct me if I'm wrong but does the label "help wanted", mean its open for anyone to fix the issue?

**Comment by XanderRubio** [comment]
> Hello, correct me if I'm wrong but does the label "help wanted", mean its open for anyone to fix the issue?

Hi @Angeltheesoto,

Yes, the help wanted tag means it is open for all contributors to assist and contribute on an open issue. A good way to get familiar with a project you might be interested in contributing and getting involved in is to read the [README](https://github.com/BeforeIDieCode/BeforeIDieAchievements#readme) and then go over the [CONTIBUTION-GUIDELINES](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md) to understand what the project is about, add your contribution, and then open a pull request. I recommend first adding your image and text of what you want to do before you die and diving into helping to grow this project! Let me know if I can assist further.

**Comment by XanderRubio** [comment]
This issue has been successfully resolved by @Angeltheesoto from pull request #85. 

In the future, to prevent multiple contributors from working on the same open issue, please ensure that you have been assigned to the issue before starting work on it. Thank you, Angel, for your valuable time and contributions to the UI enhancement!
