### ISSUE TITLE
Two new tabs are opened when click on profile

### ISSUE THREAD

**Issue by nareshkoth** [BeforeIDieCode/BeforeIDieAchievements#81]
Click on any of the profile two tabs are opening

**Comment by XanderRubio** [comment]
Hi @nareshkoth,

Thank you for expressing your interest in contributing to Before I Die Code. To familiarize yourself with the project, I recommend reviewing the [README](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/README.md) and [CONTRIBUTION-GUIDELINES.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md) documents. Afterward, you can contribute your text and image to represent your personal goal to achieve before you die. This will help you understand the git flow process.

Regarding the issue you have raised, could you please provide more details about the problem you suggest should be enhanced or fixed? For instance, are you suggesting that there is an issue when clicking on a contributor's picture, causing multiple tabs to be created? We appreciate your willingness to contribute to this open issue; however, we require that it be documented in a manner that is understandable to other developers. Please provide a clear explanation of the issue you are addressing and images. I will close this issue for now, and when you are ready to share more info on this issue please go ahead and open a new issue once again. Thank you, and have a great day!

Xander
