### ISSUE TITLE
Issue and Pull Request Templates

### ISSUE THREAD

**Issue by CBID2** [BeforeIDieCode/BeforeIDieAchievements#92]
## Problem
I noticed that this repository is missing templates for PRs and Issues. 
## Disadvantage 
This can make it difficult for people who are very new to open source to have difficulty with sharing their contribution ideas and submit them.

## Possible Solution
Create Issue templates for specific issues like Documentation, Bugs, Feature requests, Security, etc.
- See this example
```
name: General Issue
description: This template can be used for any type of issue, including bug reports, feature requests, and questions.
labels: ["general"]

body:
  ---
  **Title:** Describe your issue in a clear and concise title.
  **Description:** Provide a detailed description of your issue, including steps to reproduce it and any relevant error messages.
  **Environment:** Include information about your environment, such as the operating system, browser version, and any relevant software versions.
  **Attachments:** If possible, attach any screenshots, screen recordings, or other files that may help to diagnose the issue.
  ---

```
 For pull request templates, you can add comments on how to link issues that are addressed in the PRs, how to show the solution, and specific steps needed to ensure that contributors are submitting their PRs properly. 
 
Here's an example:

```
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
```
## Benefits
This would help new contributors develop good writing habits when raising an issue and filling out a PR form. For maintainers, these tools would help them review these requests and determine if they align with the project's purpose.

**Comment by Vijaykv5** [comment]
Yes ! That's a great Idea....Would like to work on this issue

**Comment by CBID2** [comment]
> Yes ! That's a great Idea....Would like to work on this issue

Hi @Vijaykv5. Thanks for the enthusiasm, but I wanted to do it myself. I'll gladly accept your review once I set up my PR. Sound good? Also, this [issue](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues/30) is free.

**Comment by Vijaykv5** [comment]
> > Yes ! That's a great Idea....Would like to work on this issue
> 
> Hi @Vijaykv5. Thanks for the enthusiasm, but I wanted to do it myself. I'll gladly accept your review once I set up my PR. Sound good? Also, this [issue](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues/30) is free.

Cool go on !)

**Comment by CBID2** [comment]
What do you think @XanderRubio?

**Comment by XanderRubio** [comment]
> What do you think @XanderRubio?

That's a fantastic idea, and it will certainly have a positive impact. I agree that it would be helpful for developers who are new to open source, as well as for maintainers who ensure that contributions align with the project's goals. Thank you for bringing this up @CBID2!
