### ISSUE TITLE
[Feature Request] 🎨Adding a Location Map Component Flyover feature inside the Masonry Box

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#97]
### Description

**This will be the most challenging issue that currently is an open issue**

The goal of this issue is to add a location map feature for each contributor in the MasonryBox component. When users click on a contributor's image, a map displaying the contributor's location should appear below their name and profile image. The map should have a Google Earth-like flyover effect when transitioning to the contributor's location.

To implement this feature, the following steps should be taken:

1. Create a separate LocationMap component that will display the map with the contributor's location.

2. Use a map library like Google Maps API with the Maps JavaScript API for rendering the map.
3. Use a geocoding API service like [API Ninjas](https://api-ninjas.com/api/geocoding) to convert the location value from the Contributors JSON data into latitude and longitude coordinates.
4. Integrate the LocationMap component into the [MasonryLayout](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/feature-location-map/src/Components/MasonryLayout/MasonryLayout.jsx) component.

You can either work on the existing [feature-location-map](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/feature-location-map) branch or create a new branch if you prefer a different approach. The current implementation displays the Google Maps, but the latitude and longitude coordinates for each contributor need to be fetched and displayed correctly.

Please note you will need to get API keys for Google Maps and API Ninjas. We have created a .[env.example](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/feature-location-map/.env.example) file in the repository with the following content:
```
REACT_APP_GOOGLE_MAPS_API_KEY=
REACT_APP_API_NINJAS_KEY=
```
To set up the API keys, follow these steps:
- Copy the .env.example file to a new file named .env in your local project directory.
- Replace the placeholder values with your own API keys for Google Maps and API Ninjas.
- Make sure the .env file is added to the .gitignore file to prevent it from being accidentally committed to the repository.
- By following these instructions, you can set up the required API keys and work on the feature branch without any issues.

### Screenshots

**The current Implementation on the [feature-location-map](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/feature-location-map)**
<img width="1434" alt="Screenshot 2023-09-20 at 00 28 41" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/78238ed8-04fe-4d96-b69f-653c9d38b417">
**The Data that is being returned**
<img width="1431" alt="Screenshot 2023-09-20 at 01 07 34" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/2df7fc30-402e-4cf7-918f-742957b29114">
**Issue of undefined**
<img width="1432" alt="Screenshot 2023-09-20 at 01 07 49" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/975abd97-ca96-490f-bc23-b82f6e0ccce5">

**GOAL AND AIMING HIGH FOR THE FEATURE ⬇️⬇️**

https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/93f03d40-e1db-43e2-b583-eff5abee503d

**Comment by sherikovic** [comment]
I would like to collaborate on this

**Comment by XanderRubio** [comment]
Hi @sherikovic,

Excellent, and I will go ahead and assign you to this task and be more than happy to help out if another contributor offers additional. Let me know your thoughts on approaching and ideally, the goal is to get a version similar to the Google Earth Studio flyover effect vid shown here tied to where each contributor is from. 
<img width="1415" alt="Screenshot 2023-09-20 at 16 00 20" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/54104e63-1e94-4339-9165-a0f98a984196">

**Comment by XanderRubio** [comment]
@sherikovic When needing to fetch the latest version of the `feature-location-map`:

1. Add the main repo URL as the upstream 
`git remote add upstream https://github.com/BeforeIDieCode/BeforeIDieAchievements`

2. Fetch the latest changes from the main repo
`git fetch upstream`

3. Check out the `feature-location-map` branch you want to update in your local forked repository
`git checkout feature-location-map`

4. Merge the latest changes from the main repository's feature branch into your local forked repository's `feature-location-map` branch
`git merge upstream/feature-location-map`
